factory/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from users.views import login
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls')),
    path('login/', login,name='login'),

]
if settings.DEBUG:
    urlpatterns = urlpatterns+static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)


products/urls.py
from django.urls import path
from .views import (
    home,create_maingroup,list_maingroup,create_partgroup,create_product,create_productgroup,update_maingroup,update_partgroup,
    update_product,update_productgroup,load_maingroup,delete_maingroup,delete_partgroup
    )

app_name = 'products'
urlpatterns = [
    path('',create_maingroup,name='maingroup'),
    path('main-group/<int:id>/update',update_maingroup,name='update_maingroup'),
    path('main-group/<int:id>/delete',delete_maingroup,name='delete_maingroup'),

    path('list-main-group',list_maingroup,name='list-maingroup'),

    path('part-group',create_partgroup,name='partgroup'),
    path('part-group/<int:id>/update',update_partgroup,name='update_partgroup'),
    path('part-group/<int:id>/delete',delete_partgroup,name='delete_partgroup'),

    path('product-group',create_productgroup,name='productgroup'),
    path('product-group/<int:id>/update',update_productgroup,name='update_productgroup'),

    path('product',create_product,name='product'),
    path('product/<int:id>/update',update_product,name='update_product'),


    path('ajax/dropdown-list',load_maingroup,name='ajax-dropdown'),

]


templates/login.html
{% load static %}
<link href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<div class="container">    
    <div id="loginbox" style="margin-top:50px;" class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">                    
        <div class="panel panel-info" >
                <div class="panel-heading">
                    <div class="panel-title">Login</div>
                </div>     

                <div style="padding-top:30px" class="panel-body" >

                    <div style="display:none" id="login-alert" class="alert alert-danger col-sm-12"></div>
                        
                    <form id="loginform" class="form-horizontal" role="form" method="POST">{% csrf_token %}
                                
                        <div style="margin-bottom: 25px" class="input-group">
                                    <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                                    <input id="login-username" type="text" class="form-control" name="username" value="" placeholder="username">                                        
                                </div>
                            
                        <div style="margin-bottom: 25px" class="input-group">
                                    <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                                    <input id="login-password" type="password" class="form-control" name="password" placeholder="password">
                                </div>
                                


                            <div style="margin-top:10px" class="form-group">
                                <div class="col-sm-12 controls">
                                  <button id="btn-login" class="btn btn-success">Login  </button>

                                </div>
                            </div>  
                        </form>     
                        {% if messages %}
                        {% for msg in messages %}
                        <p class="bg-red-400 text-danger rounded text-center p-1 text-sm mt-2">تکایە دڵنیابەرەوە لە راستی زانیاریەکانت!, ناوی بەکارهێنەر یان وشەی نهێنیت هەڵەیە</p>
                        {% endfor %}
                        {% endif %}


                    </div>                     
                </div>  
    </div> 
</div>

templates/main.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>کارگەی ماست</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="{% static 'css/OverlayScrollbars.min.css' %}">

  <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>

  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <link rel="stylesheet" href="{% static 'css/tempusdominus-bootstrap-4.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/icheck-bootstrap.min.css' }">
  <link rel="stylesheet" href="{% static 'css/dashboard.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/daterangepicker.css' %}">
  <link rel="stylesheet" href="https://cdn.rtlcss.com/bootstrap/v4.2.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="{% static 'css/custom.css' %}">
  <link rel="stylesheet" href="{% static 'css/buttons.bootstrap4.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/responsive.bootstrap4.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/dataTables.bootstrap4.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/alertify.css' %}">
  <link rel="stylesheet" href="{% static 'css/alertify.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/select2.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/select2-bootstrap4.min.css' %}">

  <link rel="stylesheet" href="{% static 'css/jquery.dataTables.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/jquery.dataTables.css' %}">
<style>
    @font-face {
          font-family: 'uniqadar';
          src: url('{% static 'fonts/UniQAIDAR_Hewal 004.ttf' %}');
      }
      body{
          font-family: 'uniqadar';
      }
      .select2-selection__rendered {
      line-height: 33px !important;
      }
      .select2-container .select2-selection--single {
          height: 37px !important;
      }
      .select2-selection__arrow {
          height: 36px !important;
      }      
</style>
</head>
<body class="hold-transition sidebar-mini layout-fixed">
  <div class="wrapper">

    <!-- Navbar -->
    <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
      </li>
    </ul>
      <!-- Right navbar links -->
      <ul class="navbar-nav mr-auto-navbav">
        
        <!-- Messages Dropdown Menu -->
        <li class="nav-item dropdown">
          <a class="nav-link" data-toggle="dropdown" href="#">
            <i class="far fa-comments"></i>
            <span class="badge badge-danger navbar-badge">5</span>
          </a>
        </li>
        <!-- Notifications Dropdown Menu -->
        <li class="nav-item dropdown">
          <a class="nav-link" data-toggle="dropdown" href="#">
            <i class="far fa-bell"></i>
            <span class="badge badge-warning navbar-badge">3</span>
          </a>
        </li>
      </ul>
    </nav>
    <!-- /.navbar -->
  
    <!-- Main Sidebar Container -->
    <aside class="main-sidebar sidebar-dark-primary elevation-4">
      <!-- Brand Logo -->
      <a href="index3.html" class="brand-link">
        <img src="{% static 'img/logo.jpg' %}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
             style="opacity: .8">
        <span class="brand-text font-weight-light">کارگەی ماست</span>
      </a>
  
      <!-- Sidebar -->
      <div class="sidebar">
        <!-- Sidebar user panel (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
          <div class="image">
            <img src="{{request.user.image.url}}" class="img-circle" alt="User Image">
          </div>
          <div class="info">
            <a href="#" class="d-block">{{request.user.username}}</a>
          </div>
        </div>
  
        <!-- Sidebar Menu -->
        <nav class="mt-2">
          <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
            <!-- Add icons to the links using the .nav-icon class
                 with font-awesome or any other icon font library -->
            <li class="nav-item has-treeview menu-open">
              <a href="#" class="nav-link active">
                <i class="nav-icon fab fa-product-hunt"></i>
                <p>
                  بەرهەمەکان
                  <i class="right fas fa-angle-left"></i>
                </p>
              </a>
              <ul class="nav nav-treeview">
                <li class="nav-item">
                  <a href="{% url 'products:maingroup' %}" class="nav-link {% if request.resolver_match.view_name == 'products:maingroup' %} active{% endif %}">
                    <i class="far fa-circle nav-icon"></i>
                    <p> کاڵای سەرەکی </p>
                  </a>
                </li>
                <li class="nav-item">
                  <a href="{% url 'products:partgroup' %}" class="nav-link {% if request.resolver_match.view_name == 'products:partgroup' %} active{% endif %}">
                    <i class="far fa-circle nav-icon"></i>
                    <p>گروپی فەرعی</p>
                  </a>
                </li>
                <li class="nav-item">
                  <a href="{% url 'products:productgroup' %}" class="nav-link {% if request.resolver_match.view_name == 'products:productgroup' %} active{% endif %}">
                    <i class="far fa-circle nav-icon"></i>
                    <p>گروپی کاڵا</p>
                  </a>
                </li>
                <li class="nav-item">
                  <a href="{% url 'products:product' %}" class="nav-link {% if request.resolver_match.view_name == 'products:product' %} active{% endif %}">
                    <i class="far fa-circle nav-icon"></i>
                    <p>کاڵاکان</p>
                  </a>
                </li>                
              </ul>
            </li>
            <li class="nav-item has-treeview">
              <a href="#" class="nav-link">
                <i class="nav-icon fas fa-copy"></i>
                <p>
                  ناساندنی شوێنەکان
                  <i class="fas fa-angle-left right"></i>
                </p>
              </a>
              <ul class="nav nav-treeview">
                <li class="nav-item">
                  <a href="#" class="nav-link">
                    <i class="far fa-circle nav-icon"></i>
                    <p>شارەکان</p>
                  </a>
                </li>
                <li class="nav-item">
                  <a href="#" class="nav-link">
                    <i class="far fa-circle nav-icon"></i>
                    <p>ناوچەکان</p>
                  </a>
                </li>
                <li class="nav-item">
                  <a href="#" class="nav-link">
                    <i class="far fa-circle nav-icon"></i>
                    <p>نزیکترین شوێن</p>
                  </a>
                </li>
              </ul>
            </li>
          </ul>
        </nav>
        <!-- /.sidebar-menu -->
      </div>
      <!-- /.sidebar -->
    </aside>
  
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
  
      <!-- Main content -->
      <section class="content">
        <div class="container-fluid">
          <!-- Main row -->
          <div class="row">
            {% block content %}

            {% endblock %}

          </div>
          <!-- /.row (main row) -->
        </div><!-- /.container-fluid -->
      </section>
      <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
    <!-- Control Sidebar -->
    <aside class="control-sidebar control-sidebar-dark">
      <!-- Control sidebar content goes here -->
    </aside>
    <!-- /.control-sidebar -->
  </div>
  <!-- ./wrapper -->

<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/jquery-ui.min.js' %}"></script>
<script>
  $.widget.bridge('uibutton', $.ui.button)
</script>
<script src="https://cdn.rtlcss.com/bootstrap/v4.2.1/js/bootstrap.min.js"></script>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'js/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'js/buttons.colVis.min.js' %}"></script>
<script src="{% static 'js/buttons.print.min.js' %}"></script>
<script src="{% static 'js/Chart.min.js' %}"></script>
<script src="{% static 'js/sparkline.js' %}"></script>
<script src="{% static 'js/jquery.knob.min.js' %}"></script>
<script src="{% static 'js/moment.min.js' %}"></script>
<script src="{% static 'js/daterangepicker.js' %}"></script>
<script src="{% static 'js/tempusdominus-bootstrap-4.min.js' %}"></script>
<script src="{% static 'js/jquery.overlayScrollbars.min.js' %}"></script>
<script src="{% static 'js/datatables.min.js' %}"></script>
<script src="{% static 'js/jquery.datatables.min.js' %}"></script>
<script src="{% static 'js/jquery.dataTables.js' %}"></script>
<script src="{% static 'js/dashboard.js' %}"></script>
<script src="{% static 'js/select2.full.min.js' %}"></script>

<script src="{% static 'js/inputkey.js' %}"></script>
<script src="{% static 'js/alertify.js' %}"></script>
<script src="{% static 'js/alertify.min.js' %}"></script>
{% block script %}

{% endblock %}
</body>
</html>