factory/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from users.views import login
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls')),
    path('login/', login,name='login'),

]
if settings.DEBUG:
    urlpatterns = urlpatterns+static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)


products/urls.py
from django.urls import path
from .views import (
    home,create_maingroup,list_maingroup,create_partgroup,create_product,create_productgroup,update_maingroup,update_partgroup,
    update_product,update_productgroup,load_maingroup,delete_maingroup,delete_partgroup
    )

app_name = 'products'
urlpatterns = [
    path('',create_maingroup,name='maingroup'),
    path('main-group/<int:id>/update',update_maingroup,name='update_maingroup'),
    path('main-group/<int:id>/delete',delete_maingroup,name='delete_maingroup'),

    path('list-main-group',list_maingroup,name='list-maingroup'),

    path('part-group',create_partgroup,name='partgroup'),
    path('part-group/<int:id>/update',update_partgroup,name='update_partgroup'),
    path('part-group/<int:id>/delete',delete_partgroup,name='delete_partgroup'),

    path('product-group',create_productgroup,name='productgroup'),
    path('product-group/<int:id>/update',update_productgroup,name='update_productgroup'),

    path('product',create_product,name='product'),
    path('product/<int:id>/update',update_product,name='update_product'),


    path('ajax/dropdown-list',load_maingroup,name='ajax-dropdown'),

]


products/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models import constraints
from django.db.models.base import Model
from users.models import UserAccount

class MainGroup(models.Model):
    admin = models.ForeignKey(UserAccount,on_delete=models.CASCADE)
    main_type = models.CharField(max_length=40,unique=True)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.main_type

    class Meta:
        db_table = 'maingroup'

class PartGroups(models.Model):
    admin = models.ForeignKey(UserAccount,on_delete=models.CASCADE)
    main_type = models.ForeignKey(MainGroup,on_delete=models.PROTECT,related_name='maintypes')
    part_group = models.CharField(max_length=30)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.part_group

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['main_type','part_group'],name='unique_fields')
        ]
        db_table = 'partgroups'


class ProductGroup(models.Model):
    admin = models.ForeignKey(UserAccount,on_delete=models.CASCADE)
    product_group = models.CharField(max_length=50,unique=True)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.product_group

    class Meta:
        db_table = 'productgroup'

class Products(models.Model):
    admin = models.ForeignKey(UserAccount,on_delete=models.CASCADE)
    category = models.ForeignKey(MainGroup,on_delete=models.PROTECT,related_name='category')
    part_group = models.ForeignKey(PartGroups,on_delete=models.PROTECT,related_name='partgroup')
    product_group = models.ForeignKey(ProductGroup,on_delete=models.PROTECT,related_name='productgroup')
    product_name = models.CharField(max_length=40,unique=True)
    qnt_in_box = models.IntegerField()
    kg_single = models.DecimalField(max_digits=20,decimal_places=2)
    kg_box = models.DecimalField(max_digits=20,decimal_places=2)
    info_1 = models.CharField(max_length=100,blank=True,null=True)
    info_2 = models.CharField(max_length=100,blank=True,null=True)
    info_3 = models.CharField(max_length=100,blank=True,null=True)
    date = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.product_name

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['category','part_group','product_group'],name='unique_info')
        ]
        db_table = 'products'




products/forms.py
from django.db.models import fields
from django.forms import widgets
from .models import Products,ProductGroup,PartGroups,MainGroup
from django import forms
from django.utils.translation import gettext_lazy as _

class MainGroupForm(forms.ModelForm):
    class Meta:
        model = MainGroup
        fields = ['main_type']

        error_messages = {
            'main_type':{
                'required':_('تکایە ناتوانی ئەم بەشە بە بەتاڵی بەجێ بهێڵیت'),
                'unique':_('تکایە ئەم زانیاریە داغڵکراوە'),

            }
        }
        widgets = {
            'main_type':forms.TextInput(attrs={'class':'form-control','placeholder':_('زیادکردنی ناوی گروپی سەرەکی')})
        }


class PartGroupForm(forms.ModelForm):
    main_type = forms.ModelChoiceField(queryset=MainGroup.objects.all(),empty_label=_('هەڵبژاردنی کاڵای سەرەکی'))
    class Meta:
        model = PartGroups
        fields = ['main_type','part_group']

        error_messages = {
            'main_type':{
                'required':_('تکایە ناتوانی ئەم بەشە بە بەتاڵی بەجێ بهێڵیت'),
            },
            'part_group':{
                'required':_('تکایە ناتوانی ئەم بەشە بە بەتاڵی بەجێ بهێڵیت'),
            }

        }
        widgets = {
            'part_group':forms.TextInput(attrs={'placeholder':_('ناوی گروپی فرعی')})
        }


class ProductGroupForm(forms.ModelForm):
    class Meta:
        model = ProductGroup
        fields = ['product_group']

        error_messages = {
            'product_group':{
                'required':_('تکایە ناتوانی ئەم بەشە بە بەتاڵی بەجێ بهێڵیت'),
                'unique':_('تکایە ئەم زانیاریە داغڵکراوە'),

            }
        }
        widgets = {
            'product_group':forms.TextInput(attrs={'placeholder':_('ناوی گروپی کاڵا')})
        }

class ProductsForm(forms.ModelForm):
    category = forms.ModelChoiceField(queryset=MainGroup.objects.all(),empty_label=_('هەڵبژاردنی ناوی گروپی ئەسڵی'))
    part_group = forms.ModelChoiceField(queryset=PartGroups.objects.all(),empty_label='هەڵبژاردنی ناوی گروپی فەرعی')
    product_group = forms.ModelChoiceField(queryset=ProductGroup.objects.all(),empty_label=_('هەڵبژاردنی ناوی گروپی کاڵا'))
    class Meta:
        model = Products
        fields = [
            'category','part_group','product_group','product_name','qnt_in_box','kg_single',
            'kg_box','info_1','info_2','info_3'
            ]

        error_messages = {
            'category':{
                'required':_('تکایە ناتوانی ئەم بەشە بە بەتاڵی بەجێ بهێڵیت'),
            },
            'part_group':{
                'required':_('تکایە ناتوانی ئەم بەشە بە بەتاڵی بەجێ بهێڵیت'),
            },            
            'product_group':{
                'required':_('تکایە ناتوانی ئەم بەشە بە بەتاڵی بەجێ بهێڵیت'),
            },
            'product_name':{
                'required':_('تکایە ناتوانی ئەم بەشە بە بەتاڵی بەجێ بهێڵیت'),
                'unique':_('تکایە ئەم زانیاریە داغڵکراوە'),
            },
            'qnt_in_box':{
                'required':_('تکایە ناتوانی ئەم بەشە بە بەتاڵی بەجێ بهێڵیت'),
            },            
            'kg_box':{
                'required':_('تکایە ناتوانی ئەم بەشە بە بەتاڵی بەجێ بهێڵیت'),
            },
            'kg_single':{
                'required':_('تکایە ناتوانی ئەم بەشە بە بەتاڵی بەجێ بهێڵیت'),
            },

        }
        widgets = {
            'product_name':forms.TextInput(attrs={'placeholder':_('ناوی کاڵا')}),
            'info_1':forms.TextInput(attrs={'placeholder':_('زانیاری زیادە ١')}),
            'info_2':forms.TextInput(attrs={'placeholder':_('زانیاری زیادە ٢')}),
            'info_3':forms.TextInput(attrs={'placeholder':_('زانیاری زیادە ٣')}),
            'qnt_in_box':forms.NumberInput(attrs={'placeholder':_('عەدەد لەناو کارتۆن')}),
            'kg_box':forms.NumberInput(attrs={'placeholder':_('کێشی کارتۆن')}),
            'kg_single':forms.NumberInput(attrs={'placeholder':_('کێشی دانە')}),

        }
    
    # def __init__(self,*args,**kwargs):
    #     super().__init__(*args,**kwargs)
    #     self.fields['part_group'].queryset = PartGroups.objects.all()
        # if 'category' in self.data:
        #     try:
        #         category_id = int(self.data.get('category'))
        #         self.fields['part_group'].queryset = PartGroups.objects.filter(category=category_id).all()
        #     except:
        #         pass
        
        # elif self.instance.pk:
        #     self.fields['part_group'].queryset = self.instance.category.part_group_set




products/views.py
from django import forms
from django.db.models.deletion import ProtectedError
from django.db.models.fields import json
from django.http.response import HttpResponse, JsonResponse
from django.shortcuts import render,redirect,get_object_or_404
from .models import MainGroup,PartGroups,ProductGroup,Products
from .forms import MainGroupForm,PartGroupForm,ProductGroupForm,ProductsForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core import serializers

@login_required
def create_maingroup(request):
    lists = MainGroup.objects.all().order_by('-pk')
    form = MainGroupForm()
    if request.is_ajax() and request.method == 'POST':
        form = MainGroupForm(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.admin = request.user
            obj.save()
            messages.success(request,'زیادکرا')
            return JsonResponse({'success':'success'})
        else:
            return JsonResponse({'sucess':False,'error_msg':form.errors,'error_code':'invalid'})
    context = {
        'form':form,'lists':lists
    }
    return render(request,'products/create_maingroup.html',context)

@login_required
def list_maingroup(request):
    lists = MainGroup.objects.all().order_by('-pk')
    list_serializers = serializers.serialize('json',lists)
    return HttpResponse(list_serializers,content_type='application/json')

@login_required
def update_maingroup(request,id):
    lists = MainGroup.objects.all().order_by('-pk')
    object = get_object_or_404(MainGroup,id=id)
    form = MainGroupForm(instance=object)
    if request.method == 'POST':
        form = MainGroupForm(request.POST,instance=object)
        if form.is_valid():
            form.save(commit=True)
            messages.success(request,'نوێکرایەوە')
            return redirect('products:maingroup')
    
    context = {
        'lists':lists,'form':form
    }
    return render(request,'products/update_maingroup.html',context)
                    
@login_required
def delete_maingroup(request,id):
    try:
        object = get_object_or_404(MainGroup,id=id)
        object.delete()
        messages.error(request,'سڕایەوە')
        return redirect('products:maingroup')
    except ProtectedError:
        messages.info(request,'ناتوانی ئەم ناوە بسڕیتەوە')
    return redirect('products:maingroup')


@login_required
def create_partgroup(request):
    lists = PartGroups.objects.all().order_by('-pk')
    form = PartGroupForm()
    if request.is_ajax() and request.method == 'POST':
        form = PartGroupForm(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.admin = request.user
            obj.save()
            messages.success(request,'زیادکرا')
            return JsonResponse({'success':True})
        else:
            return JsonResponse({'success':False,'error_msg':form.errors,'error_code':'invalid'})
    context = {
        'lists':lists,'form':form
    }
    return render(request,'products/create_partgroup.html',context)

@login_required
def update_partgroup(request,id):
    lists = PartGroups.objects.all().order_by('-pk')
    object = get_object_or_404(PartGroups,id=id)
    form = PartGroupForm(instance=object)
    if request.method == 'POST':
        form = PartGroupForm(request.POST,instance=object)
        if form.is_valid():
            form.save(commit=True)
            messages.success(request,'نوێکرایەوە')
            return redirect('products:partgroup')
    context = {
        'lists':lists,'form':form
    }
    return render(request,'products/update_partgroup.html',context)


@login_required
def delete_partgroup(request,id):
    try:
        object = get_object_or_404(PartGroups,id=id)
        object.delete()
        messages.error(request,'سڕایەوە')
        return redirect('products:partgroup')
    except ProtectedError:
        messages.info(request,'ناتوانی ئەم ناوە بسڕیتەوە')
    return redirect('products:partgroup')


@login_required
def create_productgroup(request):
    lists = ProductGroup.objects.all().order_by('-pk')
    form = ProductGroupForm()
    if request.is_ajax() and request.method == 'POST':
        form = ProductGroupForm(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.admin = request.user
            obj.save()
            messages.success(request,'زیادکرا')
            return JsonResponse({'success':True})
        else:
            return JsonResponse({'success':False,'error_msg':form.errors,'error_code':'invalid'})
    context = {
        'lists':lists,'form':form
    }
    return render(request,'products/create_productgroup.html',context)

@login_required
def update_productgroup(request,id):
    lists = ProductGroup.objects.all().order_by('-pk')
    object = get_object_or_404(ProductGroup,id=id)
    form = ProductGroupForm(instance=object)
    if request.method == 'POST':
        form = ProductGroupForm(request.POST,instance=object)
        if form.is_valid():
            form.save(commit=True)
            messages.success(request,'نوێکرایەوە')
            return redirect('products:productgroup')
    
    context = {
        'lists':lists,'form':form
    }
    return render(request,'products/create_productgroup.html',context)

@login_required
def create_product(request):
    lists = Products.objects.all().order_by('-pk')
    form = ProductsForm()
    if request.is_ajax() and request.method == 'POST':
        form = ProductsForm(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.admin = request.user
            obj.save()
            messages.success(request,'زیادکرا')
            return JsonResponse({'success':True})
        else:
            return JsonResponse({'success':False,'error_msg':form.errors,'error_code':'invalid'})
    context = {
        'lists':lists,'form':form
    }
    return render(request,'products/create_product.html',context)

@login_required
def update_product(request,id):
    lists = Products.objects.all().order_by('-pk')
    object = get_object_or_404(Products,id=id)
    form = ProductsForm(instance=object)
    if request.method == 'POST':
        form = ProductsForm(request.POST,instance=object)
        if form.is_valid():
            form.save(commit=True)
            messages.success(request,'نوێکرایەوە')
            return redirect('products:product')
    
    context = {'lists':lists,'form':form}
    return render(request,'products/create_product.html',context)

@login_required
def home(request):
    return render(request,'main.html')


@login_required
def load_maingroup(request):
    maingroup_id = request.GET.get('category')
    main_type = MainGroup.objects.get(id=maingroup_id)
    partgroups = PartGroups.objects.filter(main_type=maingroup_id).all()
    return render(request,'products/dropdown.html',{'partgroups':partgroups,'main_type':main_type})




products/templates/products/create_product.html
{% extends 'main.html' %}
{% load widget_tweaks %}
{% block content %}

<style>
    .selwidth{
        width: 100%;
    }

</style>
<div class="col-md-12">
    <!-- general form elements -->
    <div class="card card-info">
        <div class="card-header">
            <div class="card-tools">
                <button type="button" class="btn btn-tool" data-toggle="collapse" data-target="#product_form" aria-expanded="false" aria-controls="product_form">
                  <i class="fas fa-minus"></i>
                </button>
              </div>
            <h3 class="text-center">ناساندنی کاڵا</h3>

          </div>
      <!-- /.card-header -->
      <!-- form start -->
      <form id="product_form" role="form" method="POST" data-partgroups-url="{% url 'products:ajax-dropdown' %}">{% csrf_token %}
        <div class="card-body">
            <div class="row">
              <div class="col-md-6">
                <div class="form-group">
                  <label>گروپی سەرەکی</label>
                  {{form.category | add_class:'form-control selwidth'}}
                  <p id="category_error" class="alert alert-danger" aria-disabled="true" hidden></p>

                </div>

                <div class="form-group">
                  <label>ناوی گروپی کاڵا</label>
                  {{form.part_group | add_class:'form-control selwidth'}}
                  <p id="part_error" class="alert alert-danger" aria-disabled="true" hidden></p>

                </div>
              </div>
              <div class="col-md-6">
                <div class="form-group">
                  <label>گروپی کاڵا</label>
                  {{form.product_group | add_class:'form-control selwidth'}}
                  <p id="product_group_error" class="alert alert-danger" aria-disabled="true" hidden></p>

                </div>
     
                <div class="form-group">
                  <label>ناوی کاڵا</label>
                  {{form.product_name | add_class:'form-control'}}
                  <p id="product_name_error" class="alert alert-danger" aria-disabled="true" hidden></p>

                </div>
              </div>

              <div class="col-md-6">
                <div class="form-group">
                  <label>عەدەد لە کارتۆن</label>
                  {{form.qnt_in_box | add_class:'form-control'}}
                  <p id="qnt_in_box_error" class="alert alert-danger" aria-disabled="true" hidden></p>

                </div>
    
                <div class="form-group">
                  <label>کێشی کارتۆن</label>
                  {{form.kg_box | add_class:'form-control'}}
                  <p id="kg_box_error" class="alert alert-danger" aria-disabled="true" hidden></p>

                </div>
              </div>
              <div class="col-md-6">
                <div class="form-group">
                    <label>کێشی دانە</label>
                    {{form.kg_single | add_class:'form-control'}}
                    <p id="kg_single_error" class="alert alert-danger" aria-disabled="true" hidden></p>
  
                </div>
                <div class="form-group">
                  <label>زانیاری 1</label>
                  {{form.info_1 | add_class:'form-control'}}
                  <p id="info_1_error" class="alert alert-danger" aria-disabled="true" hidden></p>
                </div>
    
              </div>

              <!-- ---- -->
              <div class="col-md-6">
                <div class="form-group">
                    <label>زانیاری 2</label>
                    {{form.info_2 | add_class:'form-control'}}
                    <p id="info_2_error" class="alert alert-danger" aria-disabled="true" hidden></p>
  
                </div>
                </div>
                <div class="col-md-6">
                <div class="form-group">
                  <label>زانیاری 3</label>
                  {{form.info_3 | add_class:'form-control'}}
                  <p id="info_3_error" class="alert alert-danger" aria-disabled="true" hidden></p>
                </div>
    
              </div>                          
            </div>
          </div>
          <div class="card-footer">
            <button type="submit" class="btn btn-success">زیادکردن</button>
          </div>
      </form>
      
    </div>
  </div>

  <div class="col-md-12">
    <div class="card">
      <div class="card-header">
        <h3 class="text-center">زانیاریە تۆمار کراوەکان</h3>
      </div>
      <!-- /.card-header -->
      <div class="card-body table-responsive">
        <table id="maingroupid" class="table table-bordered table-striped text-center">
        <thead>              
          <tr>
            <th>#</th>
            <th>ئەدمین</th>
            <th>ناوی سەرەکی</th>
            <th>ناوی گروپی فەرعی</th>
            <th>ناوی گروپی کاڵا</th>
            <th>کاڵا</th>
            <th>عەدەد لە کارتۆن</th>
            <th>کێشی کارتۆن</th>
            <th>کێشی دانە</th>

            <th>بەروار</th>
            <th>کردارەکان</th>
          </tr>
          </thead>
          <tbody>
        {% for i in lists %}
          <tr>
            <td>{{forloop.counter}}</td>
            <td>{{i.admin}}</td>
            <td>{{i.category}}</td>
            <td>{{i.part_group}}</td>
            <td>{{i.product_group}}</td>
            <td>{{i.product_name}}</td>
            <td>{{i.qnt_in_box}}</td>
            <td>{{i.kg_box}}</td>
            <td>{{i.kg_single}}</td>

            <td>{{i.date | date:'d-m-Y h:i A'}}</td>
            <td>
                <a href="{% url 'products:update_product' i.id %}"><button><i class="far fa-edit"></i></button></a>
            </td>

        </tr>
          {% endfor %}

          </tfoot>
        </table>
      </div>
      <!-- /.card-body -->
    </div>
    <!-- /.card -->
  </div>
  
{% block script %}
    <script>
        $(document).ready(function() {
            $('#maingroupid').DataTable( {
                dom: 'Bfrtip',
                buttons: [
                    'copy','excel','pdf','print','colvis'
                ]
            } );

            $('#id_category').select2();
            $('#id_part_group').select2();
            $('#id_product_group').select2();

        } );

        {% if messages %}
        {% for msg in messages %}
            {% if msg.tags == 'success' %}
                alertify.success("{{msg}}")
            {% elif msg.tags == 'error' %}
                alertify.error("{{msg}}")          
            {% elif msg.tags == 'info' %}
                alertify.alert('ئاگاداربە! ','message')
                alertify.alert("{{msg}}",function(){            
              })
            {% endif %}
        {% endfor %}
    {% endif %}


    </script>
    
    <script>
    const form = document.getElementById('product_form')
    form.addEventListener("submit",submitHandler);

    function submitHandler(e) {
        e.preventDefault();
        $.ajax({
            type: 'POST',
            url: '{% url 'products:product' %}',
            data : $('#product_form').serialize(),
            dataType: 'json', 
            success: successFunction,
        });
    }
    function successFunction(data) {
        if (data.success) {
            form.reset();
            location.reload(true); 
        }
        else if(data.error_code=='invalid'){
            console.log(key +' : '+data.error_msg[key])
            for(var key in data.error_msg){
                if(key == 'main_type'){
                    document.getElementById('category_error').removeAttribute('hidden')
                    document.getElementById('category_error').innerHTML = data.error_msg[key][0]
                }
                else if(key == 'part_group'){
                    document.getElementById('part_error').removeAttribute('hidden')
                    document.getElementById('part_error').innerHTML = data.error_msg[key][0]                    
                }
                else if(key== 'product_group'){
                    document.getElementById('product_group_error').removeAttribute('hidden')
                    document.getElementById('product_group_error').innerHTML = data.error_msg[key][0]  
                }
                else if(key== 'product_name'){
                    document.getElementById('product_name_error').removeAttribute('hidden')
                    document.getElementById('product_name_error').innerHTML = data.error_msg[key][0]  
                }
                else if(key== 'qnt_in_box'){
                    document.getElementById('qnt_in_box_error').removeAttribute('hidden')
                    document.getElementById('qnt_in_box_error').innerHTML = data.error_msg[key][0]  
                }     
                else if(key== 'kg_single'){
                    document.getElementById('kg_single_error').removeAttribute('hidden')
                    document.getElementById('kg_single_error').innerHTML = data.error_msg[key][0]  
                }                                
                else if(key== 'kg_box'){
                    document.getElementById('kg_box_error').removeAttribute('hidden')
                    document.getElementById('kg_box_error').innerHTML = data.error_msg[key][0]  
                }                                
                else if(key== 'info_1'){
                    document.getElementById('info_1_error').removeAttribute('hidden')
                    document.getElementById('info_1_error').innerHTML = data.error_msg[key][0]  
                }    
                else if(key== 'info_2'){
                    document.getElementById('info_2_error').removeAttribute('hidden')
                    document.getElementById('info_2_error').innerHTML = data.error_msg[key][0]  
                }    
                else if(key== 'info_3'){
                    document.getElementById('info_3_error').removeAttribute('hidden')
                    document.getElementById('info_3_error').innerHTML = data.error_msg[key][0]  
                }    

            }
        }
    }


    </script>
    <script>
        $('#id_category').change(function(){
            console.log("hi")
            const url = $('#product_form').attr("data-partgroups-url");
            const categoryId = $(this).val();

            $.ajax({
                url : url,
                data:{
                    'category':categoryId
                },
                success:function(data){
                    $('#id_part_group').html(data);
                    
                }
            })

        })
    </script>
{% endblock %}
{% endblock %}

<!-- $.ajax({        
    url:'{% url 'products:list-maingroup' %}',
    type:'json',
    method:'GET',
    success:function(data){
    // $('#notify').html(data.length)
    let content='';
    for(i = 0;i < data.length; i++){

        content+='<tr>'
            +'<td>'+data[i]+'</td>'
            +'<td>'+data[i]["fields"]["admin"]+ ' : ' + check_out+ ' بۆ '+ check_in+'</td>'
            +'<td>'+data[i]["fields"]["main_type"]+ ' : ' + check_out+ ' بۆ '+ check_in+'</td>'
            +'<td>'+data[i]["fields"]["date"]+ ' : ' + check_out+ ' بۆ '+ check_in+'</td>'

            +'</div>'
    
    $(".allnotifi").html(content);
}
}}); -->

products/templates/products/create_productgroup.html
{% extends 'main.html' %}
{% load widget_tweaks %}
{% block content %}

<div class="col-md-12">
    <!-- general form elements -->
    <div class="card card-info">
      <div class="card-header">
        <div class="card-tools">
            <button type="button" class="btn btn-tool" data-toggle="collapse" data-target="#main_form" aria-expanded="false" aria-controls="main_form">
              <i class="fas fa-minus"></i>
            </button>
          </div>
        <h3 class="text-center">زیادکردنی ناوی گروپی کاڵا</h3>

      </div>
      <!-- /.card-header -->
      <!-- form start -->
      <form id="main_form" role="form" method="POST">{% csrf_token %}
        <div class="card-body">
            <div class="form-group row">
                <label for="id_product_group" class="col-sm-2 control-label">ناوی گروپی کاڵا</label>
                <div class="col-sm-10">
                  {{form.product_group | add_class:'form-control' }}
                  <p id="main_error" class="alert alert-danger" aria-disabled="true" hidden></p>
                </div>
              </div>
        </div>
        <!-- /.card-body -->
        <div class="card-footer">
            <button type="submit" class="btn btn-success">زیادکردن</button>
          </div>
      </form>
      
    </div>
  </div>

  <div class="col-md-12">
    <div class="card">
      <div class="card-header">
        <h3 class="text-center">زانیاریە تۆمار کراوەکان</h3>
      </div>
      <!-- /.card-header -->
      <div class="card-body table-responsive">
        <table id="maingroupid" class="table table-bordered table-striped text-center">
        <thead>              
          <tr>
            <th>#</th>
            <th>ئەدمین</th>
            <th>ناوی گروپی کاڵا</th>
            <th>بەروار</th>
            <th>کردارەکان</th>
          </tr>
          </thead>
          <tbody>
        {% for i in lists %}
          <tr>
            <td>{{forloop.counter}}</td>
            <td>{{i.admin}}</td>
            <td>{{i.product_group}}</td>
            <td>{{i.date | date:'d-m-Y h:i A'}}</td>
            <td>
                <a href="{% url 'products:update_productgroup' i.id %}"><button><i class="far fa-edit"></i></button></a>
            </td>

        </tr>
          {% endfor %}

          </tfoot>
        </table>
      </div>
      <!-- /.card-body -->
    </div>
    <!-- /.card -->
  </div>
  
{% block script %}

    <script>
        $(document).ready(function() {
            $('#maingroupid').DataTable( {
                dom: 'Bfrtip',
                buttons: [
                    'copy','excel','pdf','print','colvis'
                ]
            } );
        } );

        {% if messages %}
        {% for msg in messages %}
            {% if msg.tags == 'success' %}
                alertify.success("{{msg}}")
            {% else %}
                alertify.error("{{msg}}")          
            {% endif %}
        {% endfor %}
    {% endif %}


    </script>
    
{% endblock %}
{% endblock %}

<!-- $.ajax({        
    url:'{% url 'products:list-maingroup' %}',
    type:'json',
    method:'GET',
    success:function(data){
    // $('#notify').html(data.length)
    let content='';
    for(i = 0;i < data.length; i++){

        content+='<tr>'
            +'<td>'+data[i]+'</td>'
            +'<td>'+data[i]["fields"]["admin"]+ ' : ' + check_out+ ' بۆ '+ check_in+'</td>'
            +'<td>'+data[i]["fields"]["main_type"]+ ' : ' + check_out+ ' بۆ '+ check_in+'</td>'
            +'<td>'+data[i]["fields"]["date"]+ ' : ' + check_out+ ' بۆ '+ check_in+'</td>'

            +'</div>'
    
    $(".allnotifi").html(content);
}
}}); -->

products/templates/products/dropdown.html
<option value=""> هەڵبژاردنی گروپی تایبەت بە {{main_type.main_type}}</option>
{% for name in partgroups %}
<option value="{{ name.pk }}">{{ name.part_group }}</option>
{% endfor %}